In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({ "Age":
[15,18, "18",19.4, "20+"], "Gender": ["male", "female", "female", "female", "male"]})
df

    Age  Gender
0    15    male
1    18  female
2    18  female
3  19.4  female
4   20+    male

In [4]:
df.info() # Age shld be int or float but it is in object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     5 non-null      object
 1   Gender  5 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes

In [5]:
df["Age"].unique()  #'18' and '20+' are sting

array([15, 18, '18', 19.4, '20+'], dtype=object)

1. Wrong data
⚫ Solution: Replace

In [6]:
df["Age"] = df [ "Age"].replace({"20+":20})
df

    Age  Gender
0    15    male
1    18  female
2    18  female
3  19.4  female
4    20    male

In [7]:
df["Age"] = df [ "Age"].replace({"20":25,"18":18})
df

    Age  Gender
0  15.0    male
1  18.0  female
2  18.0  female
3  19.4  female
4  20.0    male

In [8]:
df.dtypes

Age       float64
Gender     object
dtype: object

In [9]:
df["Age"] = df["Age"].astype('float')
df

    Age  Gender
0  15.0    male
1  18.0  female
2  18.0  female
3  19.4  female
4  20.0    male

In [10]:
#wrong convention converting original data to some other data 
df["Age"] = df["Age"].astype('int')
df

   Age  Gender
0   15    male
1   18  female
2   18  female
3   19  female
4   20    male

In [11]:
#observe original data is preserved
df["Age"] = df["Age"].astype('float')
df

    Age  Gender
0  15.0    male
1  18.0  female
2  18.0  female
3  19.0  female
4  20.0    male

In [12]:
#2. Duplicates:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [15]:
df

    Age  Gender
0  15.0    male
1  18.0  female
2  18.0  female
3  18.0  female
4  20.0    male

In [21]:
df = pd.DataFrame({ "Age":
[15,18,18,19.4, 20], "Gender": ["male", "female", "female", "female", "male"]})
df

    Age  Gender
0  15.0    male
1  18.0  female
2  18.0  female
3  19.4  female
4  20.0    male

In [22]:
df

    Age  Gender
0  15.0    male
1  18.0  female
2  18.0  female
3  19.4  female
4  20.0    male

In [23]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [24]:
df.duplicated().sum()

1

In [25]:
df[df.duplicated()]

    Age  Gender
2  18.0  female

In [26]:
df[~df.duplicated()]

    Age  Gender
0  15.0    male
1  18.0  female
3  19.4  female
4  20.0    male

In [ ]:
#eliminate dulicated df.drop_duplicates()

In [27]:
df.drop_duplicates()

    Age  Gender
0  15.0    male
1  18.0  female
3  19.4  female
4  20.0    male

In [28]:
df=df.drop_duplicates(ignore_index=True)

In [29]:
df

    Age  Gender
0  15.0    male
1  18.0  female
2  19.4  female
3  20.0    male

In [30]:
#Missing values:
df= pd.DataFrame({"Age": [15, np.nan, 24,19,20,22],
                  "Gender": ["male", np.nan, "female", "female", np.nan, "male"]})
df

    Age  Gender
0  15.0    male
1   NaN     NaN
2  24.0  female
3  19.0  female
4  20.0     NaN
5  22.0    male

In [31]:
df.isnull()

     Age  Gender
0  False   False
1   True    True
2  False   False
3  False   False
4  False    True
5  False   False

In [32]:
df.isnull().sum()

Age       1
Gender    2
dtype: int64

In [33]:
df.isnull().sum()/len(df)*100

Age       16.666667
Gender    33.333333
dtype: float64

In [34]:

#df[condition]
df [df["Age"].isnull()]

   Age Gender
1  NaN    NaN

In [35]:
#recreate df to delete
df= pd.DataFrame({"Age": [15, np.nan, 24,19,20,22],
                  "Gender": ["male", np.nan, "female", "female", np.nan, "male"]})
df

    Age  Gender
0  15.0    male
1   NaN     NaN
2  24.0  female
3  19.0  female
4  20.0     NaN
5  22.0    male

In [36]:
df=[df.drop(index=[1])]

In [37]:
df

[    Age  Gender
 0  15.0    male
 2  24.0  female
 3  19.0  female
 4  20.0     NaN
 5  22.0    male]

In [41]:
#recreate df to delete
df= pd.DataFrame({"Age": [15, df = pd.DataFrame({ "Age":
[15,18, "18",19.4, "20+"], "Gender": ["male", "female", "female", "female", "male"]})
df, 24,19,np.nan,22],
                  "Gender": ["male", np.nan, "female", "female", np.nan, "male"]})
df

    Age  Gender
0  15.0    male
1  10.0     NaN
2  24.0  female
3  19.0  female
4   NaN     NaN
5  22.0    male

In [42]:
#to know which insex values are null
df[df["Gender"].isnull()].index.to_list()

[1, 4]

In [43]:
df[df["Age"].isnull()].index.tolist()

[4]

In [44]:
##to drop any 1 row df df.drop(index=[1])
df=df.drop(index=[1,4])
df

    Age  Gender
0  15.0    male
2  24.0  female
3  19.0  female
5  22.0    male

In [45]:
df= pd.DataFrame({"Age": [15, np.nan, 24,19,np.nan,22],
                  "Gender": ["male", np.nan, "female", "female", np.nan, "male"]})
df

    Age  Gender
0  15.0    male
1   NaN     NaN
2  24.0  female
3  19.0  female
4   NaN     NaN
5  22.0    male

In [46]:
#remove rows which are missing values
df2= df.dropna()
df2

    Age  Gender
0  15.0    male
2  24.0  female
3  19.0  female
5  22.0    male

In [47]:
df1= df.drop(columns=["Gender"])
df1

    Age
0  15.0
1   NaN
2  24.0
3  19.0
4   NaN
5  22.0

In [48]:
df = pd.DataFrame({"Age":[15, np.nan, 24,19,20,22],
"Gender": ["male", np.nan, "female", "female", np.nan, "male"]})
df

    Age  Gender
0  15.0    male
1   NaN     NaN
2  24.0  female
3  19.0  female
4  20.0     NaN
5  22.0    male

In [49]:
df["Gender"].value_counts()

Gender
male      2
female    2
Name: count, dtype: int64

In [50]:
df = pd.DataFrame({"Age":[15, np.nan, 24,19,20,22],
"Gender": ["male", np.nan, "female", "female", np.nan, "male"]})
df

    Age  Gender
0  15.0    male
1   NaN     NaN
2  24.0  female
3  19.0  female
4  20.0     NaN
5  22.0    male

In [51]:
# to fill with a value
df["Age"].fillna(20)

0    15.0
1    20.0
2    24.0
3    19.0
4    20.0
5    22.0
Name: Age, dtype: float64

In [52]:
df["Age"].mean()

20.0

In [53]:
df = pd.DataFrame({"Age":[15, np.nan, 24,19,20,22],
"Gender": ["male", np.nan, "female", "female", np.nan, "male"]})
df

    Age  Gender
0  15.0    male
1   NaN     NaN
2  24.0  female
3  19.0  female
4  20.0     NaN
5  22.0    male

In [54]:
# to fill data statistically with mean
df['Age'].fillna (df["Age"].mean())

0    15.0
1    20.0
2    24.0
3    19.0
4    20.0
5    22.0
Name: Age, dtype: float64

In [55]:
df = pd.DataFrame({"Age":[15, np.nan, 24,19,20,22],
"Gender": ["male", np.nan, "female", "female", np.nan, "male"]})
df

    Age  Gender
0  15.0    male
1   NaN     NaN
2  24.0  female
3  19.0  female
4  20.0     NaN
5  22.0    male

In [56]:
df["Age"].median()

20.0

In [57]:
## to fill data statistically with median

df=df['Age'].fillna(df["Age"].median())
df

0    15.0
1    20.0
2    24.0
3    19.0
4    20.0
5    22.0
Name: Age, dtype: float64

In [58]:
#mode will give multiple values where as mean and median give single value
df = pd.DataFrame({"Age":[15, np.nan, 24,19,20,22],
"Gender": ["male", np.nan, "female", "female", np.nan, "male"]})
df[ "Gender"].mode()

0    female
1      male
Name: Gender, dtype: object

In [ ]:
df

In [59]:
df[ "Gender"].mode()[0]

'female'

In [60]:
df["Gender"].fillna(df["Gender"].mode()[0])

0      male
1    female
2    female
3    female
4    female
5      male
Name: Gender, dtype: object