In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({"x":[1,2,3,4,5]})

In [ ]:
df

In [7]:
df = pd.DataFrame({"x":[1,2,3,4,5]})

In [5]:
#converting each value to corrending z-score is standardization
#Standardization using standard Scaler in Sklearn
#s learn is lib , preposseing is modules and satandard scaler is function
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
df['X_sc_sk'] = sc.fit_transform(df[["x"]])
df

   x   X_sc_sk
0  1 -1.414214
1  2 -0.707107
2  3  0.000000
3  4  0.707107
4  5  1.414214

In [9]:
df = pd.DataFrame({"x":[1,2,3,4,5]})
df

   x
0  1
1  2
2  3
3  4
4  5

In [10]:
#storing result in x variable 
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
df['x'] = sc.fit_transform(df[["x"]])
df

          x
0 -1.414214
1 -0.707107
2  0.000000
3  0.707107
4  1.414214

In [13]:
df = pd.DataFrame({"x":[1,2,3,4,5]})
df

   x
0  1
1  2
2  3
3  4
4  5

In [15]:
#Standardization using Pandas
df["x"] = (df["x"]-3)/1.4142135623730951
df

          x    X_sc_p
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

                                    #Min Max scaling

In [19]:
df = pd.DataFrame({"X":[11,2,33,4,5]})
df

    X
0  11
1   2
2  33
3   4
4   5

In [20]:
#MinMax Scaling using MinMaxScaler in Sklearn
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
df['X_mm_sk']=min_max.fit_transform(df[["X"]])
df

    X   X_mm_sk
0  11  0.290323
1   2  0.000000
2  33  1.000000
3   4  0.064516
4   5  0.096774

In [ ]:
df = pd.DataFrame({"X":[11,9,3,14,5]})

In [ ]:
#MinMax Scaling using MinMaxScaler in Sklearn
from sklearn. preprocessing import MinMaxScaler
min_max=MinMaxScaler()
df['X_mm_sk']=min_max.fit_transform(df[["X"]])
df

In [ ]:
df = pd.DataFrame({"X":[1,2,3,4,5]})

In [21]:
#MinMax Scaling using Pandas
df["X_mm_p"] = (df["X"]-df["X"].min()) / (df["X"].max()-df["X"].min())

In [22]:
df

    X   X_mm_sk    X_mm_p
0  11  0.290323  0.290323
1   2  0.000000  0.000000
2  33  1.000000  1.000000
3   4  0.064516  0.064516
4   5  0.096774  0.096774

In [27]:
                                    #Encoding
df1 = pd.DataFrame({"shirtsize": ["x1","small", "medium", "large", "x1", "small", "medium", "x1"]})
df1

  shirtsize
0        x1
1     small
2    medium
3     large
4        x1
5     small
6    medium
7        x1

In [24]:
df1["shirtsize"].unique()

array(['x1', 'small', 'medium', 'large'], dtype=object)

In [29]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder (categories = [["small","medium", "large", "x1"]])
df1["oe_shirtsize"] = oe.fit_transform (df1[["shirtsize"]]).astype('int')
df1

  shirtsize  oe_shirtsize
0        x1             3
1     small             0
2    medium             1
3     large             2
4        x1             3
5     small             0
6    medium             1
7        x1             3