In [1]:
import pandas as pd   #importing pandas
import numpy as np  #importing numpy

In [4]:
#Import data 
# (path +'file.csv') -- Preferred type of Loading data
df1 = pd.read_excel("liver.xlsx")
df1

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [5]:
#Import data 
# (path +'file.csv') -- Preferred type of Loading data
df2 = pd.read_csv("liver.csv")
df2

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [7]:
#Import data 
# (path +'file.csv') -- Preferred type of Loading data
df = pd.read_csv("liver.csv")
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [8]:
 #first 5 observations
df.head()

   Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0   65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1   62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2   62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3   58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4   72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1

In [10]:

#Last 5 observations
df.tail()

     Age Gender   TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
578   60   Male  0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40   Male  0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52   Male  0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31   Male  1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38   Male  1.0  0.3      216    21    24  7.3  4.4  1.50             0

In [11]:
#dimensions of the data frame
df.shape

(583, 11)

In [12]:
#Return an int representing the number of elements.
df.size

6413

In [13]:
 #column names/Variables
df.columns

Index(['Age', 'Gender', 'TB', 'DB', 'Alkphos', 'Sgpt', 'Sgot', 'TP', 'ALB',
       'AG', 'LiverPatient'],
      dtype='object')

In [14]:
#column names/Variables
df.keys() #option-2

Index(['Age', 'Gender', 'TB', 'DB', 'Alkphos', 'Sgpt', 'Sgot', 'TP', 'ALB',
       'AG', 'LiverPatient'],
      dtype='object')

In [15]:
#Data type of each column
df.dtypes

Age               int64
Gender           object
TB              float64
DB              float64
Alkphos           int64
Sgpt              int64
Sgot              int64
TP              float64
ALB             float64
AG              float64
LiverPatient      int64
dtype: object

In [16]:
#concise summary of a DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           583 non-null    int64
 1   Gender        583 non-null    object
 2   TB            583 non-null    float64
 3   DB            583 non-null    float64
 4   Alkphos       583 non-null    int64
 5   Sgpt          583 non-null    int64
 6   Sgot          583 non-null    int64
 7   TP            583 non-null    float64
 8   ALB           583 non-null    float64
 9   AG            579 non-null    float64
 10  LiverPatient  583 non-null    int64
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB

In [17]:
 #option-1
df.isnull().sum()

Age             0
Gender          0
TB              0
DB              0
Alkphos         0
Sgpt            0
Sgot            0
TP              0
ALB             0
AG              4
LiverPatient    0
dtype: int64

In [18]:
#option-2
df.isna().sum()

Age             0
Gender          0
TB              0
DB              0
Alkphos         0
Sgpt            0
Sgot            0
TP              0
ALB             0
AG              4
LiverPatient    0
dtype: int64

In [20]:
#Accessing Single column
 #option-1
df.TB

0       0.7
1      10.9
2       7.3
3       1.0
4       3.9
       ...
578     0.5
579     0.6
580     0.8
581     1.3
582     1.0
Name: TB, Length: 583, dtype: float64

In [21]:
#option-2
df['TB']

0       0.7
1      10.9
2       7.3
3       1.0
4       3.9
       ...
578     0.5
579     0.6
580     0.8
581     1.3
582     1.0
Name: TB, Length: 583, dtype: float64

In [22]:
 #option-3
df['TB'].values #output as array

array([ 0.7, 10.9,  7.3,  1. ,  3.9,  1.8,  0.9,  0.9,  0.9,  0.7,  0.6,
        2.7,  0.9,  1.1,  0.7,  0.6,  1.8,  1.6,  0.9,  0.9,  2.2,  2.9,
        6.8,  1.9,  0.9,  4.1,  4.1,  6.2,  1.1,  0.7,  4. ,  0.9,  1. ,
        2.6,  2.6,  1.3,  0.7, 14.2,  1.4,  2.7,  2.4,  0.6,  6.8,  2.6,
        1. ,  1.8,  3.9,  1.1,  0.6, 18.4,  0.7,  0.6,  3.1,  1.1,  8.9,
        8.9,  0.8,  0.9,  0.8,  1.1,  0.8,  1. ,  1. ,  0.7,  1.3,  1.4,
        2.2,  1.8,  0.7,  0.8,  0.7,  0.8,  0.8,  0.6,  0.7,  0.7,  0.9,
        0.6,  1.4,  2.8,  2.4,  1. ,  0.7,  2. ,  0.6,  1.4,  0.6,  0.8,
        0.6,  4. ,  5.7,  6.8,  8.6,  5.8,  5.2,  0.9,  3.8,  6.6,  0.6,
        0.7,  0.6,  0.7,  0.9,  0.8,  0.5,  5.3,  5.3,  0.8,  0.8,  0.9,
        0.7,  3.2,  1.2,  0.6,  5.8,  7.3,  0.7, 12.7, 15.9, 18. , 23. ,
       22.7,  1.7,  0.8,  0.6,  1.8,  5.8,  3. ,  1.7,  2.8,  3.2,  0.7,
        0.8,  0.9,  1.8, 11.3,  4.7,  0.8,  0.8,  0.8,  0.6,  4.2,  1.6,
        1.6,  3.5,  0.8,  2.9,  0.7,  0.9,  0.8,  1.1,  1.6,  0.8,  0.6,
        5.9,  8.7,  0.9,  0.7,  0.7,  1.2, 11. , 11.5,  5.8,  1.9,  1.9,
        4.5, 75. ,  3. , 22.8,  8.9,  1.7,  1.9, 14.1,  0.6,  0.6,  0.8,
        0.8, 14.8, 10.6,  8. ,  2.8,  2.9,  1.9,  0.6,  1.1,  1.5,  3.2,
        2.1,  1.9,  0.8,  6.3,  5.8,  2.3,  1.3,  2. ,  2.4,  2. ,  0.6,
        0.9, 27.2,  0.6,  0.6,  0.8,  1. ,  0.7,  2.5,  3.6,  3.9,  0.9,
        0.9,  0.8,  2.7,  2.7,  0.9,  1.7,  0.6,  0.9,  1.1,  0.6,  0.8,
        0.8,  0.9,  0.9,  1.1,  1.7,  0.6,  1.3,  0.7,  1. ,  0.6,  1.5,
        0.8,  2.7,  2. ,  0.9,  1.5,  0.8,  0.9,  0.9,  0.9,  0.7,  0.8,
        0.8,  0.9,  0.8,  0.9,  1.8,  0.9,  0.7,  1.2,  2.1,  0.9,  1.1,
        0.6,  0.7,  1.7,  0.9,  0.8,  0.8, 30.5, 16.4,  1.5,  0.8,  0.8,
        0.8,  0.9,  1.2,  0.9, 14.5,  0.6,  0.7,  0.8, 18.5,  0.7,  1.8,
        1.9,  0.9,  2. ,  2.2,  1. ,  0.8,  0.7,  0.7,  1.3,  0.9,  1.5,
        0.8,  1.3,  1. ,  4.5,  1. ,  0.7,  0.6,  1.1,  2.4,  0.6,  0.9,
        0.9,  1.1,  0.9,  0.8,  0.9,  1.7,  0.7,  0.8,  1.4,  1.6,  0.8,
        0.8,  1.1,  0.8, 23.2,  1.3,  0.8,  2. ,  0.9,  0.9,  0.7,  3.7,
        0.9,  0.7,  0.8,  1.7,  0.8,  2.6,  0.8,  1.2,  3.3,  0.8,  0.7,
        2. ,  1.7,  7.1,  0.7,  0.7,  0.7,  6.7,  2.5,  1.8,  1.4,  0.9,
        0.8,  0.8,  3.1,  0.8,  2.9,  0.6,  0.7,  1.3,  0.8,  1.8,  1.3,
        0.7,  1.4,  0.8,  1.4,  0.7,  2.1,  0.7,  0.8,  0.7,  0.7,  1.1,
        0.9,  0.8,  0.7,  0.7,  2.2,  0.8,  0.8, 22.6,  0.8,  0.7,  0.7,
        0.7,  3.5,  0.7,  0.6,  0.7,  0.7,  1.7,  0.6,  0.7,  1.4,  3.7,
        0.8,  2.7,  0.8,  0.8,  0.6,  0.8,  0.9,  7.5,  2.7,  1. ,  0.8,
        1. ,  1. ,  0.8,  1. ,  0.7,  7.3,  0.5,  0.7,  0.8,  0.8,  0.7,
        1. ,  2.4,  5. ,  1.4,  2.3,  4.9,  0.7,  1.4,  1.3,  0.6,  0.7,
        4.2,  8.2, 10.9,  1. ,  1.2,  1.6,  0.7,  0.4,  1.3,  0.9,  0.6,
        1.9,  0.7,  0.8,  0.7,  0.9,  0.7,  0.5,  1. ,  1.6,  0.8,  0.8,
        0.8,  2.3,  7.4,  0.7,  0.8,  0.9,  0.8, 23.3,  0.8,  0.9,  7.9,
        0.8,  0.9,  0.7,  0.6,  0.6,  0.7,  0.8,  6.8,  1.1,  2.2,  0.8,
        0.7,  0.8,  0.7,  0.6,  0.6,  1. ,  1. ,  0.8,  1.1,  0.6,  0.7,
        1. ,  2. ,  2.2,  0.9,  0.6,  7.1,  3.4,  0.5,  2.3,  1.1,  0.8,
        5. ,  6.7,  0.8,  0.7,  0.7,  0.8,  0.8,  1. ,  1. ,  0.7,  0.7,
        0.7,  1. ,  2.2,  1.8,  3.6,  2.7,  2.8,  0.8, 19.8, 30.5, 32.6,
       17.7,  0.9, 18.4, 20. ,  0.8,  2.2,  1. ,  0.9,  1. ,  3.9,  0.9,
        0.9,  2.9, 26.3,  1.8,  4.4,  0.8,  0.6,  0.8,  0.9,  9.4,  3.5,
        1.7,  3.3,  1.1, 30.8,  0.7,  1.4,  1.6, 19.6, 15.8,  0.8,  1.8,
        0.7,  0.8,  0.8,  0.7,  1.2,  5.5,  0.7, 20.2, 27.7, 11.1,  2.1,
        3.3,  1.2,  0.6, 10.2,  1.8,  0.8,  0.7,  2.9,  4. , 42.8, 15.2,
       16.6, 17.3,  1.4,  0.6, 22.5,  1. ,  2.7, 16.7,  7.7,  2.6,  1.1,
       15.6,  3.7, 12.1, 25. , 15. , 12.7,  0.5,  0.6,  0.8,  1.3,  1. ])

In [23]:
#Accesssing multiple colomns

#we need to pass, list of multiple columns by the column names
df[['TB','DB']]

       TB   DB
0     0.7  0.1
1    10.9  5.5
2     7.3  4.1
3     1.0  0.4
4     3.9  2.0
..    ...  ...
578   0.5  0.1
579   0.6  0.1
580   0.8  0.2
581   1.3  0.5
582   1.0  0.3

[583 rows x 2 columns]

In [24]:
#Drop a row
# Drop (Ned to specly thataxis= 0 or index, axis=1 or 'columns')
 #option-1
df1 = df.drop(0, axis=0)
df1

     Age Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
1     62   Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62   Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58   Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72   Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
5     46   Male   1.8  0.7      208    19    14  7.6  4.4  1.30             1
..   ...    ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60   Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40   Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52   Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31   Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38   Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[582 rows x 11 columns]

In [25]:
#option-2
df1 = df.drop(index = 0)
df1

     Age Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
1     62   Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62   Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58   Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72   Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
5     46   Male   1.8  0.7      208    19    14  7.6  4.4  1.30             1
..   ...    ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60   Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40   Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52   Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31   Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38   Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[582 rows x 11 columns]

In [26]:
#Drop multiple rows
#option-1
df2 = df.drop([0,1],axis=0)
df2

     Age  Gender   TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
2     62    Male  7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male  1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male  3.9  2.0      195    27    59  7.3  2.4  0.40             1
5     46    Male  1.8  0.7      208    19    14  7.6  4.4  1.30             1
6     26  Female  0.9  0.2      154    16    12  7.0  3.5  1.00             1
..   ...     ...  ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male  0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male  0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male  0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male  1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male  1.0  0.3      216    21    24  7.3  4.4  1.50             0

[581 rows x 11 columns]

In [27]:
 #option-2
df2= df.drop(index=[0,1])
df2

     Age  Gender   TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
2     62    Male  7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male  1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male  3.9  2.0      195    27    59  7.3  2.4  0.40             1
5     46    Male  1.8  0.7      208    19    14  7.6  4.4  1.30             1
6     26  Female  0.9  0.2      154    16    12  7.0  3.5  1.00             1
..   ...     ...  ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male  0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male  0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male  0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male  1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male  1.0  0.3      216    21    24  7.3  4.4  1.50             0

[581 rows x 11 columns]

In [28]:
#Drop a Colum
#option-1
df1 = df.drop("DB",axis=1)
df1

     Age  Gender    TB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0      216    21    24  7.3  4.4  1.50             0

[583 rows x 10 columns]

In [31]:
#option-2
df1 = df.drop(columns="DB")
df1

     Age  Gender    TB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0      216    21    24  7.3  4.4  1.50             0

[583 rows x 10 columns]

In [32]:
#Deleting multiple columns
#option-1
df2 = df.drop(["TB", "DB"],axis=1)
df2

     Age  Gender  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female      187    16    18  6.8  3.3  0.90             1
1     62    Male      699    64   100  7.5  3.2  0.74             1
2     62    Male      490    60    68  7.0  3.3  0.89             1
3     58    Male      182    14    20  6.8  3.4  1.00             1
4     72    Male      195    27    59  7.3  2.4  0.40             1
..   ...     ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male      500    20    34  5.9  1.6  0.37             0
579   40    Male       98    35    31  6.0  3.2  1.10             1
580   52    Male      245    48    49  6.4  3.2  1.00             1
581   31    Male      184    29    32  6.8  3.4  1.00             1
582   38    Male      216    21    24  7.3  4.4  1.50             0

[583 rows x 9 columns]

In [34]:
 #option-2
df2 = df.drop(columns=["TB","DB"])
df2

     Age  Gender  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female      187    16    18  6.8  3.3  0.90             1
1     62    Male      699    64   100  7.5  3.2  0.74             1
2     62    Male      490    60    68  7.0  3.3  0.89             1
3     58    Male      182    14    20  6.8  3.4  1.00             1
4     72    Male      195    27    59  7.3  2.4  0.40             1
..   ...     ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male      500    20    34  5.9  1.6  0.37             0
579   40    Male       98    35    31  6.0  3.2  1.10             1
580   52    Male      245    48    49  6.4  3.2  1.00             1
581   31    Male      184    29    32  6.8  3.4  1.00             1
582   38    Male      216    21    24  7.3  4.4  1.50             0

[583 rows x 9 columns]

In [35]:
#Add a new Column
df["IB"] = df["TB"]-df["DB"]
df

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient,IB
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1,0.6
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1,5.4
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1,3.2
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1,0.6
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...
578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,0,0.4
579,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1,0.5
580,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1,0.6
581,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1,0.8
582,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,0,0.7

In [36]:
df.drop(columns="IB", inplace=True)
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [37]:
#Sort Function
 #Sorting in ascending order.
df.sort_values(by='DB',ascending=True)

     Age  Gender    TB    DB  Alkphos  Sgpt  Sgot   TP  ALB   AG  LiverPatient
0     65  Female   0.7   0.1      187    16    18  6.8  3.3  0.9             1
382   58  Female   0.7   0.1      172    27    22  6.7  3.2  0.9             1
99    18    Male   0.7   0.1      312   308   405  6.9  3.7  1.1             1
98    18    Male   0.6   0.1      265    97   161  5.9  3.1  1.1             1
389   72    Male   0.6   0.1      102    31    35  6.3  3.2  1.0             1
..   ...     ...   ...   ...      ...   ...   ...  ...  ...  ...           ...
505   32    Male  32.6  14.1      219    95   235  5.8  3.1  1.1             1
259   42    Male  30.5  14.2      285    65   130  5.2  2.1  0.6             1
504   32    Male  30.5  17.1      218    39    79  5.5  2.7  0.9             1
531   40    Male  30.8  18.3      285   110   186  7.9  2.7  0.5             1
559   26    Male  42.8  19.7      390    75   138  7.5  2.6  0.5             1

[583 rows x 11 columns]

In [38]:
 #Sorting in descending order.
df.sort_values(by='TP',ascending=False)

     Age  Gender    TB    DB  Alkphos  Sgpt  Sgot   TP  ALB   AG  LiverPatient
273   30    Male   0.7   0.2      262    15    18  9.6  4.7  1.2             1
270   37    Male   0.7   0.2      235    96    54  9.5  4.9  1.0             1
519   35    Male  26.3  12.1      108   168   630  9.2  2.0  0.3             1
510   37  Female   0.8   0.2      205    31    36  9.2  4.6  1.0             0
335   13  Female   0.7   0.1      182    24    19  8.9  4.9  1.2             1
..   ...     ...   ...   ...      ...   ...   ...  ...  ...  ...           ...
533   46  Female   1.4   0.4      298   509   623  3.6  1.0  0.3             1
458   26    Male   6.8   3.2      140    37    19  3.6  0.9  0.3             1
181   75    Male   2.9   1.3      218    33    37  3.0  1.5  1.0             1
269   26    Male   0.6   0.1      110    15    20  2.8  1.6  1.3             1
180   75    Male   2.8   1.3      250    23    29  2.7  0.9  0.5             1

[583 rows x 11 columns]

#Data Extraction
This can be done by 3 ways
1. by using conditions
2. by using iloc() & loc()
3. combination of condition & loc()

In [39]:
df["Gender"]=="Male"

0      False
1       True
2       True
3       True
4       True
       ...
578     True
579     True
580     True
581     True
582     True
Name: Gender, Length: 583, dtype: bool

In [40]:
df[df["Gender"]=="Male"]

     Age Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
1     62   Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62   Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58   Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72   Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
5     46   Male   1.8  0.7      208    19    14  7.6  4.4  1.30             1
..   ...    ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60   Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40   Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52   Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31   Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38   Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[441 rows x 11 columns]

In [42]:
male_data=df[df["Gender"]=="Male"]
male_data

     Age Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
1     62   Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62   Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58   Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72   Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
5     46   Male   1.8  0.7      208    19    14  7.6  4.4  1.30             1
..   ...    ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60   Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40   Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52   Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31   Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38   Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[441 rows x 11 columns]

In [43]:
df[df['Age']>=50]

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
566   50  Female   1.0  0.3      191    22    31  7.8  4.0  1.00             0
567   52    Male   2.7  1.4      251    20    40  6.0  1.7  0.39             1
571   90    Male   1.1  0.3      215    46   134  6.9  3.0  0.70             1
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1

[230 rows x 11 columns]

In [45]:
#Multiple Conditions
filter1=df[(df['Age']==65) | (df['Gender']=="Female")]
filter1

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
6,26,Female,0.9,0.2,154,16,12,7.0,3.5,1.00,1
7,29,Female,0.9,0.3,202,14,11,6.7,3.6,1.10,1
13,74,Female,1.1,0.4,214,22,30,8.1,4.1,1.00,1
18,40,Female,0.9,0.3,293,232,245,6.8,3.1,0.80,1
...,...,...,...,...,...,...,...,...,...,...,...
547,50,Female,27.7,10.8,380,39,348,7.1,2.3,0.40,1
549,40,Female,2.1,1.0,768,74,141,7.8,4.9,1.60,1
564,38,Female,0.6,0.1,165,22,34,5.9,2.9,0.90,0
566,50,Female,1.0,0.3,191,22,31,7.8,4.0,1.00,0
568,20,Female,16.7,8.4,200,91,101,6.9,3.5,1.02,1

In [46]:
filter2=df[(df['LiverPatient']==1) & (df.Age>=70)]
filter2

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
11    72    Male   2.7  1.3      260    31    56  7.4  3.0  0.60             1
13    74  Female   1.1  0.4      214    22    30  8.1  4.1  1.00             1
71    75  Female   0.8  0.2      188    20    29  4.4  1.8  0.60             1
72    75  Female   0.8  0.2      205    27    24  4.4  2.0  0.80             1
95    75    Male   0.9  0.2      282    25    23  4.4  2.2  1.00             1
113   74    Male   0.6  0.1      272    24    98  5.0  2.0  0.60             1
157   72    Male   0.7  0.1      196    20    35  5.8  2.0  0.50             1
158   72    Male   0.7  0.1      196    20    35  5.8  2.0  0.50             1
170   72    Male   1.7  0.8      200    28    37  6.2  3.0  0.93             1
177   75    Male  14.8  9.0     1020    71    42  5.3  2.2  0.70             1
178   75    Male  10.6  5.0      562    37    29  5.1  1.8  0.50             1
179   75    Male   8.0  4.6      386    30    25  5.5  1.8  0.48             1
180   75    Male   2.8  1.3      250    23    29  2.7  0.9  0.50             1
181   75    Male   2.9  1.3      218    33    37  3.0  1.5  1.00             1
208   70  Female   0.9  0.3      220    53    95  6.1  2.8  0.68             1
224   70    Male   1.7  0.5      400    56    44  5.7  3.1  1.10             1
296   74  Female   0.9  0.3      234    16    19  7.9  4.0  1.00             1
336   75    Male   6.7  3.6      458   198   143  6.2  3.2  1.00             1
337   75    Male   2.5  1.2      375    85    68  6.4  2.9  0.80             1
338   75    Male   1.8  0.8      405    79    50  6.1  2.9  0.90             1
339   75    Male   1.4  0.4      215    50    30  5.9  2.6  0.70             1
340   75    Male   0.9  0.2      206    44    33  6.2  2.9  0.80             1
343   70    Male   3.1  1.6      198    40    28  5.6  2.0  0.50             1
348   70    Male   1.3  0.4      358    19    14  6.1  2.8  0.80             1
389   72    Male   0.6  0.1      102    31    35  6.3  3.2  1.00             1
390   72    Male   0.8  0.2      148    23    35  6.0  3.0  1.00             1
391   75    Male   0.9  0.2      162    25    20  6.9  3.7  1.10             1
396   74    Male   1.0  0.3      175    30    32  6.4  3.4  1.10             1
397   78    Male   1.0  0.3      152    28    70  6.3  3.1  0.90             1
415   70    Male   1.3  0.3      690    93    40  3.6  2.7  0.70             1
416   70    Male   0.6  0.1      862    76   180  6.3  2.7  0.75             1
429   73    Male   1.9  0.7     1750   102   141  5.5  2.0  0.50             1
500   70    Male   2.7  1.2      365    62    55  6.0  2.4  0.60             1
554   73    Male   1.8  0.9      220    20    43  6.5  3.0  0.80             1
571   90    Male   1.1  0.3      215    46   134  6.9  3.0  0.70             1

In [51]:
#iloc
# get the iva first row
df.iloc[0]

Age                 65
Gender          Female
TB                 0.7
DB                 0.1
Alkphos            187
Sgpt                16
Sgot                18
TP                 6.8
ALB                3.3
AG                 0.9
LiverPatient         1
Name: 0, dtype: object

In [52]:
df.iloc[-1]

Age               38
Gender          Male
TB               1.0
DB               0.3
Alkphos          216
Sgpt              21
Sgot              24
TP               7.3
ALB              4.4
AG               1.5
LiverPatient       0
Name: 582, dtype: object

In [53]:
 # select the first, 100th, and 500th roW
df.iloc[[3, 13,20]]

    Age  Gender   TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
3    58    Male  1.0  0.4      182    14    20  6.8  3.4  1.00             1
13   74  Female  1.1  0.4      214    22    30  8.1  4.1  1.00             1
20   51    Male  2.2  1.0      610    17    28  7.3  2.6  0.55             1

In [54]:

#Displaying multiple specified columns and rows.
df.iloc[[3, 13,20],[1,4]]

    Gender  Alkphos
3     Male      182
13  Female      214
20    Male      610

In [55]:
# select the 4th row & 3rd Column
df.iloc[3,2]

1.0

In [56]:
#Displaying specific column of range of rows.
df.iloc[:,[4,5]]

     Alkphos  Sgpt
0        187    16
1        699    64
2        490    60
3        182    14
4        195    27
..       ...   ...
578      500    20
579       98    35
580      245    48
581      184    29
582      216    21

[583 rows x 2 columns]

In [57]:
#loc
# get the first row
print(df.loc[0])

Age                 65
Gender          Female
TB                 0.7
DB                 0.1
Alkphos            187
Sgpt                16
Sgot                18
TP                 6.8
ALB                3.3
AG                 0.9
LiverPatient         1
Name: 0, dtype: object

In [58]:
df.loc [51:55]

    Age  Gender   TB   DB  Alkphos  Sgpt  Sgot   TP  ALB   AG  LiverPatient
51   34  Female  0.6  0.1      161    15    19  6.6  3.4  1.0             1
52   38    Male  3.1  1.6      253    80   406  6.8  3.9  1.3             1
53   38    Male  1.1  0.3      198    86   150  6.3  3.5  1.2             1
54   42    Male  8.9  4.5      272    31    61  5.8  2.0  0.5             1
55   42    Male  8.9  4.5      272    31    61  5.8  2.0  0.5             1

In [59]:
 #Retrieving selected rows with range
df.loc[[5,6],'TB':'TP']

    TB   DB  Alkphos  Sgpt  Sgot   TP
5  1.8  0.7      208    19    14  7.6
6  0.9  0.2      154    16    12  7.0

In [60]:
df.loc [2, "Age"]

62

In [61]:
df.iloc[2,0]

62

In [62]:
df.iloc[[4,5],0:4]

   Age Gender   TB   DB
4   72   Male  3.9  2.0
5   46   Male  1.8  0.7

In [63]:
df.loc[[4,5], "Age": "DB"]

   Age Gender   TB   DB
4   72   Male  3.9  2.0
5   46   Male  1.8  0.7

In [66]:
#Setindex
l1=df.set_index("TB")
l1

      Age  Gender   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
TB
0.7    65  Female  0.1      187    16    18  6.8  3.3  0.90             1
10.9   62    Male  5.5      699    64   100  7.5  3.2  0.74             1
7.3    62    Male  4.1      490    60    68  7.0  3.3  0.89             1
1.0    58    Male  0.4      182    14    20  6.8  3.4  1.00             1
3.9    72    Male  2.0      195    27    59  7.3  2.4  0.40             1
...   ...     ...  ...      ...   ...   ...  ...  ...   ...           ...
0.5    60    Male  0.1      500    20    34  5.9  1.6  0.37             0
0.6    40    Male  0.1       98    35    31  6.0  3.2  1.10             1
0.8    52    Male  0.2      245    48    49  6.4  3.2  1.00             1
1.3    31    Male  0.5      184    29    32  6.8  3.4  1.00             1
1.0    38    Male  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 10 columns]

In [68]:
l1.loc[0.5]

     Age  Gender   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
TB
0.5   63    Male  0.1      170    21    28  5.5  2.5  0.80             1
0.5   42  Female  0.1      162   155   108  8.1  4.0  0.90             1
0.5   17  Female  0.1      206    28    21  7.1  4.5  1.70             0
0.5    7    Male  0.1      352    28    51  7.9  4.2  1.10             0
0.5   60    Male  0.1      500    20    34  5.9  1.6  0.37             0

In [69]:
l1.loc[1.0, 'DB':'ALB']

      DB  Alkphos  Sgpt  Sgot   TP  ALB
TB
1.0  0.4      182    14    20  6.8  3.4
1.0  0.3      187    19    23  5.2  2.9
1.0  0.3      208    17    15  7.0  3.6
1.0  0.5      158    37    43  7.2  3.6
1.0  0.5      158    37    43  7.2  3.6
1.0  0.3       75    25    26  5.1  2.9
1.0  0.3      142    27    21  6.4  3.5
1.0  0.3      202    26    13  5.3  2.6
1.0  1.4      144    18    14  8.3  4.2
1.0  0.5      239    16    39  7.5  3.7
1.0  0.3      250    48    44  8.6  4.3
1.0  0.3      310    37    56  5.9  2.5
1.0  0.3      175    30    32  6.4  3.4
1.0  0.3      152    28    70  6.3  3.1
1.0  0.2      205   137   145  6.0  3.0
1.0  0.2      719   157   108  7.2  3.7
1.0  0.3      163    48    71  7.1  3.7
1.0  0.3      212    41    80  6.2  3.1
1.0  0.3       90    18   108  6.8  3.1
1.0  0.3      190    30    54  5.3  2.1
1.0  0.3      154    38    21  6.8  3.9
1.0  0.3      180    56   111  6.8  3.9
1.0  0.3      805   133   103  7.9  3.3
1.0  0.2      189    52    31  8.0  4.8
1.0  0.3      195    22    28  5.8  2.6
1.0  0.3      230    48    58  8.4  4.2
1.0  0.3      191    22    31  7.8  4.0
1.0  0.3      216    21    24  7.3  4.4

In [70]:
l1.reset_index()

       TB  Age  Gender   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     0.7   65  Female  0.1      187    16    18  6.8  3.3  0.90             1
1    10.9   62    Male  5.5      699    64   100  7.5  3.2  0.74             1
2     7.3   62    Male  4.1      490    60    68  7.0  3.3  0.89             1
3     1.0   58    Male  0.4      182    14    20  6.8  3.4  1.00             1
4     3.9   72    Male  2.0      195    27    59  7.3  2.4  0.40             1
..    ...  ...     ...  ...      ...   ...   ...  ...  ...   ...           ...
578   0.5   60    Male  0.1      500    20    34  5.9  1.6  0.37             0
579   0.6   40    Male  0.1       98    35    31  6.0  3.2  1.10             1
580   0.8   52    Male  0.2      245    48    49  6.4  3.2  1.00             1
581   1.3   31    Male  0.5      184    29    32  6.8  3.4  1.00             1
582   1.0   38    Male  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]