In [11]:
import pandas as pd   #importing pandas
import numpy as np  #importing numpy

In [8]:
#Pandas Series
#Create Series using List
l=['banana', 42]
s=pd.Series(l)
print(s)

0    banana
1        42
dtype: object

In [12]:
s=pd.Series(l, index=['a','b'])
print(s)

a    banana
b        42
dtype: object

In [13]:
#. Create Series using Array
a=np.array(1)
s=pd.Series(a, index=['a','b'])
print(s)

a    1
b    1
dtype: int32

In [14]:
#3. Create Series using Dictionary
d = {'a': 1,'b': 2,'c': 3}
ser= pd.Series(d)
ser

a    1
b    2
c    3
dtype: int64

In [15]:
d = {'a': 1,'b': 2, 'c': 3}
ser = pd.Series(d, index=['a','c'])
ser

a    1
c    3
dtype: int64

In [16]:
d = {'coll': [1, 2], 'col2': [3, 4]}
df = pd.Series(d)
df

coll    [1, 2]
col2    [3, 4]
dtype: object

In [18]:
                                #Data Frame --> pandas.DataFrame
#1. Create DataFrame using Dictionary
d = {'coll': [1, 2], 'co12': [3, 4]}
df = pd.DataFrame(d)
df

   coll  co12
0     1     3
1     2     4

In [19]:
#2. Create DataFrame using Nested List or 2D array
temperature_df = pd.DataFrame({
"city": ["mumbai","delhi", "banglore", 'hyderabad'], "temperature": [32,45,4,36]})

print(temperature_df)

        city  temperature
0     mumbai           32
1      delhi           45
2   banglore            4
3  hyderabad           36

In [20]:
#Attributes
#Displaying the dimensions of the data frame using shape.
temperature_df.shape

(4, 2)

In [21]:
#Displaying the size of the data frame using size.
temperature_df.size

8

In [23]:
 #Displaying the name of the columns
temperature_df.columns

Index(['city', 'temperature'], dtype='object')

In [24]:
#Displaying the name of the columns using keys () function.
temperature_df.keys()

Index(['city', 'temperature'], dtype='object')

In [25]:
 temperature_df.dtypes

city           object
temperature     int64
dtype: object

In [32]:
#Adac Add a column
#adding column named "Mobile" to the data frame.
temperature_df["AQI"] =[120,160,100,80]
temperature_df

        city  temperature  AQI
0     mumbai           32  120
1      delhi           45  160
2   banglore            4  100
3  hyderabad           36   80

In [33]:
#Drop a row
#Drop (Need to specify that axis = 0 or 'index', axis=1 or 'columns')
 #Deleting row from the data frame
df=temperature_df.drop(index=[0])
df

        city  temperature  AQI
1      delhi           45  160
2   banglore            4  100
3  hyderabad           36   80

In [34]:
#Deleting multiple rows from the data frame
df=temperature_df.drop(index=[0,1])
df

        city  temperature  AQI
2   banglore            4  100
3  hyderabad           36   80

In [31]:
#Drop a column
#Drop (Need to specify that axis = 0 or 'index', axis=1 or 'columns')
df = temperature_df.drop(columns=["AQr","city"])
df

KeyError: "['AQr'] not found in axis"

In [35]:
df = temperature_df.drop("AQI", axis=1)
df

        city  temperature
0     mumbai           32
1      delhi           45
2   banglore            4
3  hyderabad           36

In [36]:
#temperature_df = temperature_df.drop("AQI",axis=1)
temperature_df

        city  temperature  AQI
0     mumbai           32  120
1      delhi           45  160
2   banglore            4  100
3  hyderabad           36   80

In [37]:
temperature_df.drop("city",axis=1,inplace=True)
temperature_df

   temperature  AQI
0           32  120
1           45  160
2            4  100
3           36   80

In [38]:
 temperature_df = pd.DataFrame({
"city": ["mumbai","delhi","banglore", 'hyderabad'],
 "temperature": [32,45,4,36]})

temperature_df

        city  temperature
0     mumbai           32
1      delhi           45
2   banglore            4
3  hyderabad           36

In [41]:
humidity_df = pd.DataFrame ({
 "city": ["delhi","mumbai", "banglore"],
 "humidity": [68, 65, 75]})
humidity_df

       city  humidity
0     delhi        68
1    mumbai        65
2  banglore        75

In [42]:
                                                    #Combining Dataframes
#option 1: Append

#a Adding rows to the data frame by ading another data frame
df = temperature_df.append(humidity_df)
df

AttributeError: 'DataFrame' object has no attribute 'append'

In [44]:
temperature_df.append(humidity_df)

AttributeError: 'DataFrame' object has no attribute 'append'

In [45]:
#option 2: Concatenate
df = pd.concat([temperature_df, humidity_df])
df

        city  temperature  humidity
0     mumbai         32.0       NaN
1      delhi         45.0       NaN
2   banglore          4.0       NaN
3  hyderabad         36.0       NaN
0      delhi          NaN      68.0
1     mumbai          NaN      65.0
2   banglore          NaN      75.0

In [47]:
#if you want continuous index

df = pd.concat([temperature_df, humidity_df],ignore_index=True)
df

        city  temperature  humidity
0     mumbai         32.0       NaN
1      delhi         45.0       NaN
2   banglore          4.0       NaN
3  hyderabad         36.0       NaN
4      delhi          NaN      68.0
5     mumbai          NaN      65.0
6   banglore          NaN      75.0

In [48]:
df = pd.concat([temperature_df, humidity_df],axis=1)
df

        city  temperature      city  humidity
0     mumbai           32     delhi      68.0
1      delhi           45    mumbai      65.0
2   banglore            4  banglore      75.0
3  hyderabad           36       NaN       NaN

In [49]:
#Merging of DataFrame
#Inner Join
df = pd.merge(temperature_df, humidity_df, on='city',how="inner")
df

       city  temperature  humidity
0    mumbai           32        65
1     delhi           45        68
2  banglore            4        75

In [51]:
#Outer Join
df = pd.merge(temperature_df, humidity_df, on='city', how="outer")
df

        city  temperature  humidity
0     mumbai           32      65.0
1      delhi           45      68.0
2   banglore            4      75.0
3  hyderabad           36       NaN

In [52]:
#Import data 
# (path +'file.csv') -- Preferred type of Loading data
df = pd.read_csv("liver.csv")
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [53]:
#Import data 
# (path +'file.csv') -- Preferred type of Loading data
df = pd.read_excel("liver.xlsx")
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]